server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://192.168.153.128:3306/boot
    username: springBoot
    password: springBoot
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    properties:
      hibernate:
        format_sql: true
